[project]
name = "langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.11.0",
    "isort>=7.0.0",
    "langchain-ollama>=1.0.0",
    "langchain-openai>=1.0.3",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "langchain",
]

[tool.uv.sources]
langchain = { workspace = true }
